/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.llmops.controller;import cn.zhuatech.llmops.common.ApiResponse;import cn.zhuatech.llmops.service.ModelDeploymentGovernanceService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                        */
@RestController @RequestMapping("/api/enterprise/llmops")public class ModelDeploymentGovernanceController{private final ModelDeploymentGovernanceService service;/**
                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                         */
public ModelDeploymentGovernanceController(ModelDeploymentGovernanceService service){this.service=service;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
@PostMapping("/model-deployment")public ApiResponse<ModelDeploymentGovernanceService.Assessment>assess(@Valid @RequestBody ModelDeploymentGovernanceService.Request request){return ApiResponse.ok(service.assess(request));}}
