/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.llmops.service;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.assertThat;/**
                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                               */
class ModelDeploymentGovernanceServiceTest{private final ModelDeploymentGovernanceService service=new ModelDeploymentGovernanceService();/**
                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                        */
@Test void deploysGovernedModel(){var r=service.assess(new ModelDeploymentGovernanceService.Request("R1",true,true,true,true,0,true,true,true,60));assertThat(r.decision()).isEqualTo(ModelDeploymentGovernanceService.Decision.DEPLOY);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
@Test void blocksSafetyAndGovernanceFailures(){var r=service.assess(new ModelDeploymentGovernanceService.Request("R2",false,false,false,false,2,false,true,true,60));assertThat(r.blockers()).hasSize(6);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
@Test void usesCanaryForOperationalRisk(){var r=service.assess(new ModelDeploymentGovernanceService.Request("R3",true,true,true,true,0,true,false,false,95));assertThat(r.actions()).hasSize(3);}}
