/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.llmops.config;
import cn.zhuatech.llmops.model.*; import cn.zhuatech.llmops.repository.*; import org.springframework.boot.CommandLineRunner; import org.springframework.context.annotation.*; import org.springframework.security.crypto.password.PasswordEncoder; import java.time.LocalDate; import java.util.List;
@Configuration public class DataInitializer {
 @Bean CommandLineRunner seed(OperatingUnitRepository units,WorkRecordRepository records,ResourceRegisterRepository resources,ReviewRecordRepository reviews,UserRepository users,PasswordEncoder encoder){return args->{if(units.count()>0)return;
  OperatingUnit knowledge=units.save(new OperatingUnit("LLM-KB","知识智能空间","数字化中心",200)),service=units.save(new OperatingUnit("LLM-CS","客户服务空间","客户服务部",160)),marketing=units.save(new OperatingUnit("LLM-MKT","营销智能空间","品牌市场部",120));
  WorkRecord a=records.save(new WorkRecord("REL-260801-028","APP-KNOWLEDGE-RAG","企业知识助手模型升级",knowledge,120,108,3,LocalDate.now().plusDays(1),WorkRecord.Status.RUNNING,"PROMPT-V12")); WorkRecord b=records.save(new WorkRecord("REL-260801-021","APP-AICC-SUMMARY","客服摘要模型提示升级",service,86,86,0,LocalDate.now(),WorkRecord.Status.COMPLETED,"PROMPT-V8")); WorkRecord c=records.save(new WorkRecord("REL-260731-096","APP-MKT-COPY","营销文案模型安全回归",marketing,200,146,12,LocalDate.now(),WorkRecord.Status.RELEASED,"PROMPT-V6"));
  resources.saveAll(List.of(new ResourceRegister("MODEL-GENERAL-L","通用大语言模型 L",knowledge,ResourceRegister.Status.RUNNING,99),new ResourceRegister("MODEL-FAST-S","轻量低时延模型 S",service,ResourceRegister.Status.RUNNING,98),new ResourceRegister("MODEL-EMBED-CN","中文向量模型 E",marketing,ResourceRegister.Status.ALARM,76)));
  reviews.saveAll(List.of(new ReviewRecord("EVAL-LLM-260801",a,"综合质量",120,3,ReviewRecord.Result.PENDING,"季衡"),new ReviewRecord("EVAL-LLM-260728",b,"业务效果",86,0,ReviewRecord.Result.PASSED,"顾清和"),new ReviewRecord("EVAL-LLM-260726",c,"内容安全",200,12,ReviewRecord.Result.FAILED,"季衡")));
  String demo=encoder.encode("Demo@2026"); users.saveAll(List.of(new UserAccount("operator",demo,"顾清和",UserAccount.Role.DOMAIN_USER,"LLM-KB"),new UserAccount("planner",demo,"季衡",UserAccount.Role.DOMAIN_OPERATOR,null),new UserAccount("quality",demo,"顾清",UserAccount.Role.QUALITY,null),new UserAccount("admin",encoder.encode("ZhuaTech@2026"),"系统管理员",UserAccount.Role.ADMIN,null)));};}
}
